import assert from 'node:assert/strict'
import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 950 } })
const errors = [], api = []
page.on('pageerror', error => errors.push(error.message))
page.on('request', request => { if (request.url().includes('/api/')) api.push(request.url()) })
await page.goto('http://127.0.0.1:5173/onboarding-preview')
const button = name => page.getByRole('button', { name, exact: true })
const input = name => page.getByRole('textbox', { name, exact: true })
const progress = () => page.locator('.ob-progress')
assert.equal(await progress().count(), 0, 'start screen has no counter')
await button('Continuar com email').click()
assert.equal(await progress().getAttribute('aria-label'), 'Passo 1 de 6')
assert.equal(await progress().locator('span').count(), 6)
await button('Continuar com email').click()
assert.equal(await page.getByRole('alert').textContent(), 'Introduz um endereço de email válido.', 'an empty email raises the toast, not the browser bubble')
await page.getByRole('button', { name: 'Fechar' }).click()
await input('Endereço de email').fill('mateus@example.com')
await button('Continuar com email').click()
assert.equal(await progress().getAttribute('aria-label'), 'Passo 2 de 6')
await button('Continuar com código').click()
assert.equal(await page.getByRole('alert').textContent(), 'Introduz o código de seis dígitos enviado por email.', 'an empty code raises the toast')
await input('Código de confirmação').fill('12')
await button('Continuar com código').click()
assert.equal(await progress().getAttribute('aria-label'), 'Passo 2 de 6', 'a short code holds the step')
await page.getByRole('button', { name: 'Fechar' }).click()
await input('Código de confirmação').fill('123456')
await button('Continuar com código').click()
assert.equal(await progress().getAttribute('aria-label'), 'Passo 3 de 6')
await input('Nome').fill('Fontes Editorial')
assert.equal(await input('URL do ambiente').inputValue(), 'fontes-editorial')
await page.reload()
assert.equal(await input('Nome').inputValue(), 'Fontes Editorial')
assert.equal(await progress().getAttribute('aria-label'), 'Passo 3 de 6', 'counter survives a reload')
await page.screenshot({ animations: 'disabled', path: '/tmp/fontes-onboarding-preview/workspace.png' })
await button('Criar ambiente').click()
await input('Nome do perfil').fill('Mateus Costa')
await button('Criar perfil').click()
assert.equal(await progress().getAttribute('aria-label'), 'Passo 5 de 6')
await input('Emails dos membros').fill('not-an-email')
await button('Enviar convite por email').click()
assert.equal(await page.getByRole('alert').textContent(), 'Confirma os endereços de email dos convites.', 'a bad invite raises the error toast')
assert.equal(await progress().getAttribute('aria-label'), 'Passo 5 de 6', 'and holds the step')
await page.getByRole('button', { name: 'Fechar' }).click()
assert.equal(await page.getByRole('alert').count(), 0, 'the toast closes')
await input('Emails dos membros').fill('ana@example.com\nines@example.com')
await button('Enviar convite por email').click()
await page.getByRole('switch', { name: /Changelog/ }).check()
assert.equal(await page.getByRole('switch', { name: /Resumos diários/ }).isChecked(), false)
await page.screenshot({ animations: 'disabled', path: '/tmp/fontes-onboarding-preview/updates.png' })
await button('Começar').click()
await page.getByText('Pré-visualização concluída.').waitFor()
await button('Reiniciar').click()
await button('Login').click()
await page.getByRole('heading', { name: 'Perfil existente' }).waitFor()
assert.equal(await progress().getAttribute('aria-label'), 'Passo 1 de 2', 'login only confirms the identity')
await input('Endereço de email').fill('mateus@example.com')
await button('Continuar com email').click()
await input('Código de confirmação').fill('123456')
await button('Continuar com código').click()
await page.getByText('Pré-visualização concluída.').waitFor()
await button('Reiniciar').click()
await button('Continuar com Google').click()
await page.getByRole('heading', { name: 'Novo ambiente de trabalho' }).waitFor()
assert.equal(await progress().getAttribute('aria-label'), 'Passo 1 de 4', 'Google skips the email screens')
assert.equal(await progress().locator('span').count(), 4)
await button('Reiniciar').click()
await page.setViewportSize({ width: 390, height: 844 })
for (const name of ['Início', 'Email', 'Código', 'Ambiente', 'Perfil', 'Convites', 'Atualizações']) {
  await page.getByRole('navigation', { name: 'Ecrãs' }).getByRole('button', { name, exact: true }).click()
  assert.ok(await page.locator('.ob-panel').evaluate(el => el.getBoundingClientRect().right <= innerWidth), name)
}
await page.getByRole('navigation', { name: 'Ecrãs' }).getByRole('button', { name: 'Atualizações', exact: true }).click()
await page.screenshot({ animations: 'disabled', path: '/tmp/fontes-onboarding-preview/mobile.png' })
assert.deepEqual(errors, [])
assert.deepEqual(api, [])
await browser.close()
console.log('Passed: signup, login, per-path step counter, persistence, preferences, error toast, 7 mobile screens, no API requests or browser errors.')
